name: peak_mind
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  youtube_player_flutter: ^9.1.3
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.0
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/
    - assets/logos/
    - assets/subjects/